package org.kimp;

import java.util.HashMap;
import java.util.LinkedList;

/**
 * Singleton queue which contains and manage tickets
 */
public class TicketQueue {
    private HashMap<Integer, Ticket> tickets = new HashMap<>();
    private static TicketQueue instance;

    static {
        instance = new TicketQueue();
    }

    /**
     * @return singleton queue object
     */
    public static TicketQueue getInstance() {
        return instance;
    }

    /**
     * Represent a ticket (number and service type)
     */
    public static class Ticket {
        private int number;
        private TicketType type;

        /**
         * Creates new ticket (just TicketQueue can create Tickets)
         * @param number Number for the ticket (generated by queue)
         * @param type Type of requested service
         */
        private Ticket(int number, TicketType type) {
            this.number = number; this.type = type;
        }

        public TicketType getType() {
            return type;
        }

        public int getNumber() {
            return number;
        }
    }

    /**
     * Creates new ticket and send it to the queue
     * @param type Service type for the ticket
     * @return Created ticket
     */
    public Ticket addTicket(TicketType type) {
        int n = tickets.keySet().size();
        if (n != 0) n = (int)tickets.keySet().toArray()[n - 1];
        do {
            n = n + 1;
        } while (tickets.containsKey(n) == true);
        tickets.put(n, new Ticket(n, type));
        return tickets.get(n);
    }

    /**
     * Proceed the first ticket
     */
    public Ticket popTicket() {
        if (tickets.keySet().size() == 0) return null;
        Ticket res = null;
        try {
            res = tickets.get(tickets.keySet().toArray()[0]);
            return res;
        } finally {
            tickets.remove(res.getNumber());
        }
    }

    /**
     * @return Array of tickets in the queue
     */
    public Ticket [] getTickets() {
        Ticket [] res = new Ticket[tickets.keySet().size()];
        int counter = 0;
        for (var key : tickets.keySet()) {
            res[counter] = tickets.get(key);
            counter += 1;
        }
        return res;
    }

    /**
     * Proceed specific ticket
     * @param number Number of the ticket
     */
    public Ticket popTicket(int number) {
        if (tickets.containsKey(number) == false) return null;
        try {
            return tickets.get(number);
        } finally {
            tickets.remove(number);
        }
    }
}
